export { default as Message } from './Message'
export { default as Form } from './Form'
export { default as Form2 } from './Form2'
export { default as FormTest } from './FormTest'
export { default as TitleArea } from './TiltleArea'
export { default as ContentArea } from './ContentArea'
export { default as InputArea } from './InputArea'
